/**
 * Duração padrão (dias) por label_pt do tipo de atividade.
 * Chave em MAIÚSCULAS para comparação case-insensitive.
 * Fonte: especificação técnica Linha 6 — Zitrón Brasil.
 */
export const ACTIVITY_DEFAULT_DURATIONS: Record<string, number> = {
  'GRELHA DE ENTRADA DE AR PRESSURIZAÇÃO': 1,
  'REGISTRO CORTAFOGO + SOBREPRESSÃO': 2,
  'ATENUADOR ANTES DO VENTILADOR DUTO 1': 2,
  'ATENUADOR ANTES DO VENTILADOR DUTO 2': 2,
  'ATENUADOR APÓS DO VENTILADOR DUTO 1': 3,
  'ATENUADOR APÓS DO VENTILADOR DUTO 2': 3,
  'ATENUADOR ANTES DO VENTILADOR EXAUSTÃO D3': 2,
  'ATENUADOR ANTES DO VENTILADOR EXAUSTÃO D4': 2,
  'ATENUADOR ANTES DO VENTILADOR INSUFLAÇÃO D1': 2,
  'ATENUADOR ANTES DO VENTILADOR INSUFLAÇÃO D2': 2,
  'ATENUADOR APOS DO VENTILADOR EXAUSTÃO D3': 3,
  'ATENUADOR APOS DO VENTILADOR EXAUSTÃO D4': 3,
  'ATENUADOR APOS DO VENTILADOR INSUFLAÇÃO D1': 3,
  'ATENUADOR APOS DO VENTILADOR INSUFLAÇÃO D2': 3,
  'ATENUADOR ANTES DO VENTILADOR EXAUSTÃO': 5,
  'ATENUADOR ANTES DO VENTILADOR INSUFLAÇÃO': 5,
  'ATENUADOR APÓS DO VENTILADOR INSUFLAÇÃO': 6,
  'ATENUADOR APÓS DO VENTILADOR EXAUSTÃO': 6,
  'ATENUADOR ANTES DO VENTILADOR': 11,
  'ATENUADOR APÓS DO VENTILADOR': 11,
  'GRELHAS PRESSURIZAÇÃO NA CAIXA DA ESCADA': 6,
  'GRELHAS EMBAIXO PLATAFORMA 1': 7,
  'GRELHAS EMBAIXO PLATAFORMA 2': 7,
  'DUTOS PRESSURIZAÇÃO + VENTILADORES CENTRÍFUGOS + DAMPERS DE RETORNO': 4,
  'ELECTROCALHAS + PAINEIS + C. FORÇA + C. SENSOR. CORTA FOGO. + ELETRODUTOS': 8,
  'ELECTROCALHAS + PAINEIS + C. FORÇA + C. CONTROLE + C. S. TEMP + ELETRODUTOS + S. TEMP': 10,
  'VENTILADORES AXIAIS + CALDELERIA DUTO 1': 7,
  'VENTILADORES AXIAIS + CALDELERIA DUTO 2': 7,
  'VENTILADORES AXIAIS + CALDELERIA EXAUSTÃO D3': 4,
  'VENTILADORES AXIAIS + CALDELERIA EXAUSTÃO D4': 4,
  'VENTILADORES AXIAIS + CALDELERIA INSUFLAÇÃO D1': 4,
  'VENTILADORES AXIAIS + CALDELERIA INSUFLAÇÃO D2': 4,
  'VENTILADORES AXIAIS + CALDELERIA EXAUSTÃO': 14,
  'VENTILADORES AXIAIS + CALDELERIA INSUFLAÇÃO': 14,
  'VENTILADORES AXIAIS + CALDELERIA': 14,
  'DUTOS VIA 1': 14,
  'DUTOS VIA 2': 14,
};

export function getDefaultDuration(labelPt: string): number | undefined {
  return ACTIVITY_DEFAULT_DURATIONS[labelPt.toUpperCase().trim()];
}
